In [1]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib
from scipy import signal
import random

import h5py
from IPython.utils import io

In [2]:
%matplotlib widget

In [3]:
import sys
sys.path.append('../../../../nadavp/new_trap/Tools/')
sys.path.append('../../../../nadavp/new_trap/Tools/StatFramework/')
import BeadDataFile
from discharge_tools import *

In [4]:
%reload_ext autoreload
%autoreload 2

In [5]:
from likelihood_calculator import likelihood_analyser
from likelihood_calculator import GravityFramework
from likelihood_calculator import auxiliary_functions as aux
gfw = GravityFramework.GravityFramework()

## Discahrge

In [6]:
bdf_discharge = load_dir(dirname='/data/new_trap/20200921/Bead1/Discharge/FineDischarge_after_TF/')

300  files in folder
300  files loaded


In [7]:
bb = bdf_discharge[0]
bb.electrode_channels

array([1, 2], dtype=uint16)

In [7]:
dis_z = [np.std(bb.response_at_freq2('z', drive_freq=71)) for bb in bdf_discharge]

In [8]:
ch = [bb.electrode_channels[0] for bb in bdf_discharge]

In [29]:
_,ax = plt.subplots(figsize=(9.1,4))
ax.scatter(range(len(dis_z)), dis_z/dis_z[0], label='std')
ax.scatter(range(len(dis_z)), amps/amps[0], label='fit')
ax.legend()

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [9]:
bdf_discharge_z = [bb for bb,ch_ in zip(bdf_discharge, ch)  if ch_==1 ]
bdf_discharge_x = [bb for bb,ch_ in zip(bdf_discharge, ch)  if ch_==4 ]

In [10]:
index_z = [bb for bb,ch_ in zip(range(len(bdf_discharge)), ch)  if ch_==1 ]
index_x = [bb for bb,ch_ in zip(range(len(bdf_discharge)), ch)  if ch_==4 ]

In [12]:
m1 = gfw.build_z_response(bdf_discharge_z, drive_freq=71, charges=1, bandwidth=1, bimodal=False)

***************************************************
Z2-amplitude:  1.12e+03
reduced chi2:  3584.1562360793614
***************************************************
Z2-amplitude:  1.14e+03
reduced chi2:  2056.475519108972
***************************************************
Z2-amplitude:  1.10e+03
reduced chi2:  2634.4619942522068
***************************************************
Z2-amplitude:  1.12e+03
reduced chi2:  2640.0084595424937
***************************************************
Z2-amplitude:  1.11e+03
reduced chi2:  2926.2235240014465
***************************************************
Z2-amplitude:  1.09e+03
reduced chi2:  3579.601294022411
***************************************************
Z2-amplitude:  1.13e+03
reduced chi2:  4079.3970480358166
***************************************************
Z2-amplitude:  1.11e+03
reduced chi2:  5704.452719666814
***************************************************
Z2-amplitude:  1.11e+03
reduced chi2:  3560.347171646013
**************

***************************************************
Z2-amplitude:  4.23e+02
reduced chi2:  6667.67154713797
***************************************************
Z2-amplitude:  4.23e+02
reduced chi2:  16872.212563131972
***************************************************
Z2-amplitude:  9.83e+01
reduced chi2:  7957.320523122175
***************************************************
Z2-amplitude:  1.08e+02
reduced chi2:  11455.683859634393
***************************************************
Z2-amplitude:  4.83e+01
reduced chi2:  23051.26593546717
***************************************************
Z2-amplitude:  6.52e+01
reduced chi2:  7694.170495943105
***************************************************
Z2-amplitude:  5.18e+01
reduced chi2:  6511.6187023623
***************************************************
Z2-amplitude:  4.80e+01
reduced chi2:  21186.028468833098
***************************************************
Z2-amplitude:  3.79e+01
reduced chi2:  20895.077354307272
******************

***************************************************
Z2-amplitude:  2.07e+02
reduced chi2:  1707.4588430302344
***************************************************
Z2-amplitude:  2.24e+02
reduced chi2:  1388.3017859457975
***************************************************
Z2-amplitude:  2.44e+02
reduced chi2:  2992.910909129134
***************************************************
Z2-amplitude:  2.33e+02
reduced chi2:  2281.802029373557
***************************************************
Z2-amplitude:  2.07e+02
reduced chi2:  2590.2521461288065
***************************************************
Z2-amplitude:  2.11e+02
reduced chi2:  720.592085484291
***************************************************
Z2-amplitude:  2.19e+02
reduced chi2:  2400.530457935582
***************************************************
Z2-amplitude:  2.12e+02
reduced chi2:  1584.9384470504506
***************************************************
Z2-amplitude:  2.16e+02
reduced chi2:  1389.1393970247004
***************

In [15]:
m2 = gfw.build_x_response(bdf_discharge_x, drive_freq=71, charges=1, bandwidth=1)

***************************************************
X2-amplitude:  1.22e+01
reduced chi2:  1.5077204319970472
***************************************************
X2-amplitude:  1.22e+01
reduced chi2:  1.6561307426139402
***************************************************
X2-amplitude:  1.23e+01
reduced chi2:  1.2313121190426974
***************************************************
X2-amplitude:  1.22e+01
reduced chi2:  1.16464891136188
***************************************************
X2-amplitude:  1.21e+01
reduced chi2:  1.2168587862400966
***************************************************
X2-amplitude:  1.22e+01
reduced chi2:  1.2696742562620946
***************************************************
X2-amplitude:  1.23e+01
reduced chi2:  1.458111243801847
***************************************************
X2-amplitude:  1.23e+01
reduced chi2:  1.2708153177285613
***************************************************
X2-amplitude:  1.22e+01
reduced chi2:  1.4039743199327412
*************

In [11]:
dis_x = [np.std(bb.response_at_freq('x', drive_freq=71)) for bb in bdf_discharge_x]
dis_z = [np.std(bb.response_at_freq2('z', drive_freq=71)) for bb in bdf_discharge_z]

In [16]:
ampsx = np.array([m_.values[0] for m_ in m2])
phasesx = np.array([m_.values[2] for m_ in m2])
_, ax = plt.subplots(1,2,figsize=(9.1,4))
ax[0].scatter(range(len(ampsx)), ampsx)
ax[1].scatter(range(len(ampsx)), phasesx)
np.mean(phases[20:50])

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

3.1700000000000004

In [12]:
_,ax = plt.subplots(figsize=(9.5,4))
scale = 74
scale2 = 50
scaleX = -0.8
scaleX2 = 9200

# Perrinf
# ax.scatter(index_z, amps/scale, label='fit fixed-phase')
ax.scatter(index_z, np.array(dis_z)/scale2, label='Z response')
# ax.scatter(index_x, ampsx/scaleX, label='X response')
ax.scatter(index_x, np.array(dis_x)/scaleX2, label='X-pos fit fixed-phases')

ax.legend()
ax.set(xlabel='dataset', ylabel='Charges', ylim=(None,None), xlim=(None,None))
ax.grid(axis='y')
ax.minorticks_on()
ax.grid(which='major', linestyle='-', linewidth='0.5', color='red')
ax.grid(which='minor', linestyle=':', linewidth='0.5', color='black')
ax.legend()
from matplotlib.ticker import MaxNLocator
ax.yaxis.set_major_locator(MaxNLocator(integer=True))

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

## TF

In [6]:
# 7.6um German bead
fname = r'/home/data_transfer/data_from_windows/20200921/Bead1/TransFunc/TransFuncX2_1Hz_300s.h5'
tf_x = BeadDataFile.BeadDataFile(fname=fname)
fname = r'/home/data_transfer/data_from_windows/20200921/Bead1/TransFunc/TransFuncY1_1Hz_100s.h5'
tf_y = BeadDataFile.BeadDataFile(fname=fname)
fname = r'/home/data_transfer/data_from_windows/20200921/Bead1/TransFunc/TransFuncZ2_1Hz_300s.h5'
tf_z = BeadDataFile.BeadDataFile(fname=fname)
tf_list = [tf_x, tf_y, tf_z]

No height data
No cantilever data
Error loading spinning data
No laser power data
No height data
No cantilever data
Error loading spinning data
No laser power data
No height data
No cantilever data
Error loading spinning data
No laser power data


In [8]:
_,ax = plt.subplots(1,3, figsize=(9,3))
bb = tf_z
ax[0].semilogy(*bb.psd2('x'))
ax[1].semilogy(*bb.psd2('y'))
ax[2].semilogy(*bb.psd2('z'))
[a.set(xlim=(0,100)) for a in ax]

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

[[(0.0, 100.0)], [(0.0, 100.0)], [(0.0, 100.0)]]

In [50]:
names = ['Y2', 'Y3', 'Y4', 'Y5', 'Y6', 'Y7', 'Y8', 'Y9']
names = ['Y7', 'Y8', 'Y9', 'Y11']
fnames = [r'/home/data_transfer/data_from_windows/20200921/Bead1/TransFunc/TransFunc'+y_+'_7Hz_10s.h5' for y_ in names]
bbs = [BeadDataFile.BeadDataFile(fname_) for fname_ in fnames]

No height data
No cantilever data
Error loading spinning data
No laser power data
No height data
No cantilever data
Error loading spinning data
No laser power data
No height data
No cantilever data
Error loading spinning data
No laser power data
No height data
No cantilever data
Error loading spinning data
No laser power data


In [56]:
_,ax = plt.subplots()
[ax.semilogy(*bb.psd2('y'), label=name_) for bb,name_ in zip(bbs,names)]
ax.legend()
ax.set(xlim=(100,1000))
tmp_freq, tmp_psd = bbs[-1].psd2('x')
np.sqrt(tmp_psd[tmp_freq==71]/tmp_psd[tmp_freq==50])

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

array([2.06282349])

## Nois floor

In [18]:
bdf_z = bdf_discharge[245:260]
bdf_x = bdf_discharge[240:245]

freq = bdf_z[0].psd2('z')[0]
z_scale1 = bdf_z[0].psd2('z')[1][freq==71]
for bb in bdf_z:
    z_scale1 += bb.psd2('z')[1][freq==71]
z_scale1 /= len(bdf_z)

x_scale1 = bdf_x[0].psd2('x')[1][freq==71]
for bb in bdf_x:
    x_scale1 += bb.psd2('x')[1][freq==71]
x_scale1 /= len(bdf_x)

charges = 4
force = charges * 1.6e-19 * 20 / 8.6e-3 * 0.63 * np.sqrt(10) # in Newtons/sqrt(Hz)
z_scale1 = force/np.sqrt(z_scale1)
x_scale1 = force/np.sqrt(x_scale1)

In [48]:
del data_bdfs

In [46]:
## 100 files of shaking data for nose floor
num_files = 500
data_bdfs = load_dir(dirname='/data/new_trap/20200921/Bead1/Discharge/HeightControl2/', 
                         file_prefix='Discharge_', start_file=500, max_file=num_files)
freq = data_bdfs[0].psd2('x')[0]
fftx1 = data_bdfs[0].psd2('x')[1]
ffty1 = data_bdfs[0].psd2('y')[1]

fftz1 = data_bdfs[0].psd2('z')[1]
for i in range(1,num_files):
    fftx1 += data_bdfs[i].psd2('x')[1]
    fftz1 += data_bdfs[i].psd2('z')[1]
    ffty1 += data_bdfs[i].psd2('y')[1]
fftx1/=num_files
ffty1/=num_files
fftz1/=num_files

1308  files in folder
500  files loaded


In [49]:
_,ax = plt.subplots(1,2,figsize=(9.1,4), sharex=True)
# tf_freq = np.interp(freq, gfw.tf_freq, gfw.tf_ffts[2])
ax[0].semilogy(freq, np.sqrt(fftx1)*x_scale1)
ax[1].semilogy(freq, np.sqrt(fftz1)*z_scale1)
ax[0].set(xlim=(1,500), ylim=(9e-18,1e-14), xlabel='Frequency [Hz.]', ylabel=r'ASD [N/$\sqrt{Hz}$]', title='X force')
_ = ax[1].set(xlim=(1,500), ylim=(9e-18,1e-14), xlabel='Frequency [Hz.]', title=r'Z force')
# print(np.sqrt(fftx1[freq==18])*x_scale/np.sqrt(10), np.sqrt(fftz1[freq==18])*z_scale/np.sqrt(10))

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [18]:
mm_mle_scale

array([5.25, 5.21, 5.17, 5.19, 5.18, 5.2 , 5.25, 5.22, 5.17, 5.23, 5.22,
       5.28, 5.3 , 5.29, 5.25, 5.26, 5.21, 5.24, 5.23, 5.24, 5.22, 5.15,
       5.22, 5.23, 5.24, 5.14, 5.11, 5.03, 5.09, 5.17, 5.16, 5.21, 5.24,
       5.19, 5.09, 5.14, 5.12, 5.17, 5.22, 5.18, 5.2 , 5.21, 5.2 , 5.17,
       5.16, 5.28, 5.26, 5.14, 5.22, 5.16, 5.18, 5.16, 5.19, 5.26, 5.23,
       5.22, 5.15, 5.02, 5.2 , 5.01, 5.09, 5.09, 5.16, 5.06, 5.13, 5.09,
       5.14, 5.08, 5.13, 5.2 , 5.09, 5.09, 5.09, 5.08, 5.09, 5.22, 5.19,
       5.11, 5.06, 5.16, 5.17, 5.13, 5.1 , 5.12, 5.05, 5.2 , 5.14, 5.1 ,
       5.1 , 5.  , 5.06, 5.15, 5.12, 5.13, 5.16, 5.13, 5.2 , 5.22, 5.07,
       5.14])

In [13]:
def func1_height(i):
    print(i,'  ******************')
    fname = r'/data/new_trap/20200921/Bead1/Discharge/HeightControl2/Discharge_'+str(i)+'.h5'
    bb = BeadDataFile.BeadDataFile(fname=fname)
    return np.mean(bb.feedback[2])

In [7]:
func1_height(10)

10   ******************


5.22

In [14]:
from joblib import Parallel, delayed
from tqdm import tqdm
test1_zfb = Parallel(n_jobs=20)(delayed(func1_height)(i) for i in tqdm(range(1700)))


100%|██████████| 1700/1700 [00:42<00:00, 31.32it/s]

In [16]:
_,ax = plt.subplots(figsize=(9.2,4))
ax.scatter(range(1700), test1)

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [17]:
i = 1400
fname = r'/data/new_trap/20200921/Bead1/Discharge/HeightControl2/Discharge_'+str(i)+'.h5'
bb = BeadDataFile.BeadDataFile(fname=fname)

In [18]:
f = h5py.File(fname,'r')
pos_data = np.array(f['pos_data'])
quad_data = np.array(f['quad_data'])

In [20]:
sync = pos_data.reshape(-1,11).T[5]

In [21]:
_,ax = plt.subplots(figsize=(9.5,4))
ax.plot(range(500), sync[:500]/100)

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [62]:
i_start = np.nonzero(sync[:500])[0][0]
zfb = bb.feedback[2][i_start-1:]
x_sync = bb.xyz[0][i_start-1:]

In [65]:
_,ax = plt.subplots(figsize=(9.2,4))
ax.plot(range(40000), zfb[100000:140000]/np.mean(zfb[:40000]), label='z_fb')
ax.plot(range(40000), bb.z2[100000:140000]/np.mean(bb.z2[:40000])*50-49, 'r--',label='z', alpha=(0.5))
ax.plot(range(40000), bb.Iz[100000:140000]/np.mean(bb.Iz[:40000])*50-49,label='Iz', alpha=(0.5))
ax.legend()

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [58]:
_,ax = plt.subplots(figsize=(9.2,4))
# ax.plot(range(40000), x_sync[:40000]/np.mean(x_sync[:40000]), label='z_fb')
ax.plot(range(40000), bb.z2[100000:140000]/np.mean(bb.z2[:40000]), 'r--',label='Iz', alpha=(0.5))
ax.legend()

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …